### ISSUE TITLE
Pods Issue StarIO for 2.8.2 - Signature not valid in the specified time frame: Start [Sun, 31 May 2020 15:00:00 GMT] - Expiry [Thu, 30 Dec 2021 15:00:00 GMT] - Current [Tue, 04 Jan 2022 05:35:05 GMT]

### ISSUE THREAD

**Issue by sehaswaran** [star-micronics/StarPRNT-SDK-iOS-Swift#12]
As per Cocoapods spec,
for StarIO for 2.8.2
https://github.com/CocoaPods/Specs/commit/801136a3fd67b3edb0b29eb0b6168cc1b70d5403

path is mentioned as "https://libraryfilesstorage.blob.core.windows.net/ios/StarIO/2.8.2/StarIO.zip?sv=2019-02-02&si=TechSalesSupp&sr=c&sig=kkD24MYypOKNgnika6m1dHueNNbGz%2Bk0WQ8%2BuYO%2B0TM%3D"

This server is not working

We are getting the error as

Signature not valid in the specified time frame: Start [Sun, 31 May 2020 15:00:00 GMT] - Expiry [Thu, 30 Dec 2021 15:00:00 GMT] - Current [Tue, 04 Jan 2022 05:35:05 GMT]

For StarIO for 2.9.0

https://github.com/CocoaPods/Specs/commit/742a9a589a8f7bd66c73ce715974cdeed21dae68#diff-874fd2b761d9e117e081b137d1499e5ac15b69ca8b47496becec687760132117

it is using new server

https://library.starmicronicscloud.com/ios/StarIO/2.9.0/StarIO.zip

Could you please update for 2.8.2 also ?

**Comment by gare-bear** [comment]
@sehaswaran Do you need the older version of StarIO for any specific reason? 
If not, then i'd suggest using 2.9.0.

**Comment by sehaswaran** [comment]
2.8.2 we already have in production. 

We would like to use 2.9.0 by following specific process (Unit Testing).

In PodSpec file of 2.8.2 version ,

we might need to change the correct path 
https://library.starmicronicscloud.com/ios/StarIO/2.8.2/StarIO.zip


https://github.com/CocoaPods/Specs/commit/801136a3fd67b3edb0b29eb0b6168cc1b70d5403

**Comment by gare-bear** [comment]
and what if you update the url yourself? does that not work?

**Comment by sehaswaran** [comment]
Closing this. 
I have started using 2.9.0

**Comment by prajwal2100** [comment]
@sehaswaran Did the StarIO 2.8.2 work ?
I am having the exact same issue as you, how did you solve this issue?

**Comment by bandit-ibayashi** [comment]
@prajwal2100 Would it be possible to use the latest version of StarIO? There is backward compatibility between 2.8.2 and 2.9.1.

StarIO from 2.8.0 to 2.8.2 are not available at this time due to some problems with the upload procedure and because we have not found a way to update the URL for the relevant version. Since these StarIOs have been out for some time, we would like you to use its latest version.
https://github.com/star-micronics/StarPRNT-SDK-iOS-Swift/issues/22#issuecomment-1381213844
