### ISSUE TITLE
CPU usage above 90%!!!

### ISSUE THREAD

**Issue by WenzhaoTan-Chowbus** [star-micronics/StarPRNT-SDK-iOS-Swift#13]
SDK Version: 5.14.2
iOS Version: 13.3.1

When searching for printers, the CPU usage will exceed 90%.

**Comment by Tatsuki-Yamamoto2731** [comment]
@WenzhaoTan-Chowbus Thank you for your report.
We have reproduced this issue. We will investigate the root cause and consider improvement.

**Comment by Tatsuki-Yamamoto2731** [comment]
We have fixed this issue in the latest version (StarIO Ver.2.10.0).
Again, thank you for your report.
