### ISSUE TITLE
SPM Support [BUG]

### ISSUE THREAD

**Issue by John-Connolly** [star-micronics/StarPRNT-SDK-iOS-Swift#19]
## Description
The included XCFramework does not work with Swift package manager.  When integrating as a binary target in a swift package, SPM throws the error.  
```
Cannot open file handle for file at path: Path(str: "/Sources/Frameworks/StarIO_Extension.xcframework/ios-arm64_i386_x86_64-simulator/StarIO_Extension.framework")

```
This is due to no top-level info plist on for the .framework files. Also, the info.plist in the fat framework resources folder is not processed.

## Your device where the bug occurs 
N/A

## Your printer
N/A

## Your development environment

```
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79
```

## To Reproduce
I have attached a sample project to reproduce quickly.  Open the "App" Xcode project in the attached zip
and build to replicate.

## Additional context
Add any other context about the bug here.

[SPM-import-issue.zip](https://github.com/star-micronics/StarPRNT-SDK-iOS-Swift/files/9261155/SPM-import-issue.zip)

**Comment by bandit-ibayashi** [comment]
We understand your request, and the framework included in the successor StarXpand SDK supports the Swift Package Manager, but StarIO requires a different configuration and does not support it.

SPM support is summarized in the previously posted Issue #2, so this issue will be closed.

Thank you for your understanding.
