### ISSUE TITLE
Suggestion: Add StarPRNT emulation for Stargraphic printers

### ISSUE THREAD

**Issue by johnnyshields** [star-micronics/StarPRNT-SDK-iOS-Swift#20]
Currently, Stargraphic-only models such as the TSP100 series can only accept raster printing commands.

It would be amazing if Star could support an emulation driver in iOS/Android that supports StarPRNT commands such as `append`, `appendAlignment`, `enableEmphasis`, etc., renders/rasterizes the text into an image in iOS memory, and outputs the raster image bytes to the device.

**Comment by bandit-ibayashi** [comment]
Sorry for not responding for a long time regarding this matter.

Thank you for your suggestion.
However, considering future maintenance and our strategy, we regret to inform you that we have no plans to support this at this time.
We are afraid for not being able to meet your expectations, but we hope for your understanding.
