### ISSUE TITLE
[BUG] App built with Xcode 14 causes crash when calling disconnect

### ISSUE THREAD

**Issue by monolithic-adam** [star-micronics/StarPRNT-SDK-iOS-Swift#21]
## Description
A clear and concise description of what a bug is. disconnect

## Your device where the bug occurs 
 - Device: 
    Any iPad
 - OS:
    iOS 14, 15, 16

## Your printer
- Model Names:
    mPOP
- Firmware Version:
    4.0
- Interface:
   bluetooth

## Your development environment
The result of executing the command `ver` on Windows, `sw_vers` on macOS, `uname –a` on Linux, or these equivalent commands.
ProductName:	macOS
ProductVersion:	12.5.1
BuildVersion:	21G83

## To Reproduce
1. Call disconnect on StarIoExtManager

## Expected behavior
not crash

## Screenshots
N/A

## Additional context
Add any other context about the bug here.
Crash Log
```
3
POS
StarIoExtManager.m - 行 53
-[StarIoExtManager .cxx_destruct] + 53
4
libobjc.A.dylib
object_cxxDestructFromClass(objc_object*, objc_class*) + 116
6
libobjc.A.dylib
_objc_rootDealloc + 80
7
POS
StarIoExtManager.m - 行 121
-[StarIoExtManager dealloc] + 121
``` 

Happens about 44% while the app is in the background (with background operations on)

**Comment by gare-bear** [comment]
@monolithic-adam Looking into it.

**Comment by gare-bear** [comment]
@monolithic-adam I've compiled a bunch of apps since you opened this issue, and I haven't reprodued any crashes. 
Does this happen with the sample app? Or just your own app?

**Comment by gare-bear** [comment]
@monolithic-adam i'm going to close this issue for now, but if you are still having this issue, we can re-open it.

**Comment by monolithic-adam** [comment]
@gare-bear Sorry I couldn't answer sooner, we got busy on another feature's development and this crash got put on the backburner, we are still having this issue in our app but I haven't tried the sample app because tbh we cannot reproduce it when testing, we are getting alot of crash reports on Firebase for it and were hoping that others were facing the same issue.

**Comment by monolithic-adam** [comment]
@gare-bear 
I edited the Issue to give it a bit more detail in the Issue description, the symbolicated crash has to do with a semaphore that was deallocated while in use. I hope it helps a little!
