### ISSUE TITLE
Missing privacy manifest?

### ISSUE THREAD

**Issue by amcalgates** [star-micronics/StarPRNT-SDK-iOS-Swift#25]
## Description
According [Apple docs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc):

> From Fall 2023 you’ll receive an email from Apple if you upload an app to App Store Connect that uses required reason API without describing the reason in its privacy manifest file. From Spring 2024, apps that don’t describe their use of required reason API in their privacy manifest file won’t be accepted by App Store Connect.

Does StarPRNT-SDK use any APIs mentioned here? If so, are there plans to include a privacy manifest? I'm not 100% sure what that'd even look like, but [this thread](https://developer.apple.com/forums/thread/733537) maybe has a little insight.

## Your device where the bug occurs 
 - Device: 
Any
 - OS:
Any
 - Browser: 
N/A
 - Version
N/A

## Your printer
- Model Names:
Any
- Firmware Version:
Any
- Interface:
Any

## Your development environment
N/A

## To Reproduce
N/A
## Expected behavior
N/A

## Screenshots
N/A

## Additional context
N/A

**Comment by Tatsuki-Yamamoto2731** [comment]
@amcalgates Thank you for your report.
StarPRNT SDK uses User Defaults APIs that are mentioned in Apple's guideline.
Therefore, we have updated StarPRNT SDK to V5.17.1, which includes the privacy manifest file.
