### ISSUE TITLE
SM-T300i Connection

### ISSUE THREAD

**Issue by 15mgm15** [star-micronics/StarPRNT-SDK-iOS-Swift#26]
## Description
I am creating a Xamarin.iOS binding of your library, but, while calling:

SearchPrinter("BLE:") **I am getting an empty array.**

SearchPrinter("BL:") / SearchPrinter("ALL:") **Doesn't return any port.**

Using your StarPRNT SDK iOS app I am able to connect the printer and print an example ticket.

I have these permissions already on my info.plist:

<key>NSBluetoothPeripheralUsageDescription</key>
<string>Please allow access to Bluetooth to connect to 3rd party devices.</string>
<key>NSBluetoothAlwaysUsageDescription</key>
<string>Please allow access to Bluetooth to connect to 3rd party devices.</string>
<key>UISupportedExternalAccessoryProtocols</key>
<array>
	<string>jp.star-m.starpro</string>
</array> 

## Your device where the bug occurs 
 - Device: 
    iPhone 13 Pro Max
 - OS:
    iOS 17.2

## Your printer
- Model Names:
    SM-T300i
- Interface:
    Bluetooth

## Your development environment
Mac OS, Xamarin.iOS, Visual Studio for Mac

Using the deprecated Xamarin library, I am also not able to connect, but I am able to connect to the old SM-T300 model. 

I have also tried to bind the StarXpand library to Xamarin, but there is a Factory method that returns an instance of an abstract class which doesn't translate well from Swift to C# 

Please let me know your comments.

**Comment by bandit-ibayashi** [comment]
@15mgm15 We are afraid we have not tested it with Xamarin at this time and cannot guarantee that it will work.

But there are two points from your report that concern me. Could you please confirm these points first?

1. Would your iOS device be paired with SM-T300i?

    The SM-T300i connects to the host device via Bluetooth, not BLE. Therefore, pairing is required in advance. [`SMPort.searchPrinter()`](https://www.star-m.jp/products/s_print/sdk/starprnt_sdk/manual/ios_swift/en/api_stario_port.html#searchprinter) method will return the connected printers.
    Please refer to the following for pairing information.
    https://www.star-m.jp/products/s_print/sdk/starprnt_sdk/manual/ios_swift/en/getting_start.html#bluetooth

2. Could you please specify `("BT:")` instead of `("BL:")` for the searchPrinter argument?

Thank you in advance.

**Comment by bandit-ibayashi** [comment]
We are afraid this issue is closed as there has been no movement for over 6 months. If you continue to have issues, please let us know.
