### ISSUE TITLE
Search returns an empty array

### ISSUE THREAD

**Issue by arturdev** [star-micronics/StarPRNT-SDK-iOS-Swift#3]
```Swift
SMPort.searchPrinter(target: "ALL:") as? [PortInfo]
```
This returns an empty array, though the sample app works.
What can be the issue?

**Comment by gare-bear** [comment]
@arturdev what connection type does your printer have?

**Comment by arturdev** [comment]
it is a bluetooth printer

**Comment by arturdev** [comment]
@gare-bear 

PrinterSetting
{
    portName: BT:TSP100
    portSettings: 
    macAddress: 00:11:62:18:35:61
    modelName: TSP143IIIBI GY
    emulation: 3
    cashDrawerOpenActiveHigh: true
    allReceiptsSettings: 7
    selectedPaperSize: threeInch
    selectedModelIndex: tsp100
}

**Comment by gare-bear** [comment]
@arturdev there are two key/value pairs you should add to your plist plist to ensure you have the proper permission to discover Bluetooth printers. 

- **supported external accessory protocol** -  so you can discover the printer using searchPrinter
- **Privacy - Bluetooth Always Usage Description** - a description shown to the user when you want to request permission to use a Bluetooth printer

This is mentioned in section 2 of our [documentation](https://www.star-m.jp/products/s_print/sdk/starprnt_sdk/manual/ios_swift/en/configure_application.html#information-property-list)

Check if these are missing from your plist

**Comment by arturdev** [comment]
The second one is added, but the first one is missing. Let me add it and try again

**Comment by gare-bear** [comment]
@arturdev any luck?

**Comment by arturdev** [comment]
The person who owns the printer is in a different timezone, I'm waiting for him. Will report back as soon as he tests it.

Thanks for your interest, appreciate that ❤️

**Comment by arturdev** [comment]
After adding the missing entry to the info.plist, now it is able to find the printer. The printing returns success status code but nothing is printed in reality. Trying to figure out what is the issue. 
Thanks

**Comment by arturdev** [comment]
It seems correct. I'm using the same function for printing as in the demo app.
https://github.com/star-micronics/StarPRNT-SDK-iOS-Swift/blob/master/SDK/Swift%20SDK/Communications/Communication.swift#L28

And the `completionHandler` is being called with `SMStarIOResultCodeSuccess` but nothing is printed.

**Comment by gare-bear** [comment]
@arturdev You're probably trying to print text which the TSP143III doesn't support.
This particular printer is Raster only, so you must send your data in graphical form using a UIImage. 
Then use the [ISCBBuilder](https://www.star-m.jp/products/s_print/sdk/starprnt_sdk/manual/ios_swift/en/api_starioext_i_command_builder.html#)  and the [appendBitmap](https://www.star-m.jp/products/s_print/sdk/starprnt_sdk/manual/ios_swift/en/api_starioext_i_command_builder.html#appendbitmap) method to print the image.
Here you can find the [supported methods for each model](https://www.star-m.jp/products/s_print/sdk/starprnt_sdk/manual/ios_swift/en/api_starioext_i_command_builder.html).

**Comment by arturdev** [comment]
Yes, I was trying to print a text. So I need to programmatically check what type the currently connected printer supports (text/image/etc..) and build the print-data accordingly, right?

**Comment by gare-bear** [comment]
Exactly! You can use the **ModelCapability** class to determine what emulation the printer supports. Just FYI the correct emulation is **starGraphic**.

**Comment by arturdev** [comment]
@gare-bear Hi again. 
I'm having some issue when I'm printing second time in a row.
First time it prints successfully. But second time it doesnt. 

My flow is the following:

When user prints, I'm creating `StarIoExtManager` instance with the selected printer port settings.
Then, sending commands (I'm using the same Communications class which is in this demo project).
The second time I'm getting `errorOpenPort`. 
Is there anything wrong I'm doing?

**Comment by arturdev** [comment]
@gare-bear Can you help, please?

**Comment by gare-bear** [comment]
@arturdev please post this as a new issue and i'll be happy to help you. please post your code as well.
