### ISSUE TITLE
Bothscale for StarDotImpact

### ISSUE THREAD

**Issue by ImTung** [star-micronics/StarPRNT-SDK-iOS-Swift#5]
Hello, I'm using Star SP700 (Star Dot Impact) for my kitchen order and TSP800II for Receipt.

Because our order has multiple languages, so, for easy we convert to image and using `appendBitmap` command for printing.
In the TSP800 device, it works perfectly. But in the SP700, the image not scale, it's so big.
![Image](https://user-images.githubusercontent.com/13881055/110737645-576a7d00-8260-11eb-8509-b214a0db46dd.JPG)

My pager: 3'', and I set in `appendBitmap` command with is 576dots.

Please help.

**Comment by ImTung** [comment]
oh, my bad, SP700 is 210dots

**Comment by gare-bear** [comment]
Hi @ImTung,

Glad you found your answer. For others, you can reference pixel width from our PrinterSettingConstant class

https://github.com/star-micronics/StarPRNT-SDK-Android-Java/blob/23a400e8292721fbff772e8b6fc73dc0db40e08b/SDK/app/src/main/java/com/starmicronics/starprntsdk/PrinterSettingConstant.java#L15-L20

**Comment by radhika-gokani** [comment]
On what is paper size defined ? Any kind of printer can be connected so how to decide which size to use ?
