### ISSUE TITLE
Cannot find TSP100GT printer that's shared through network

### ISSUE THREAD

**Issue by stan96D** [star-micronics/StarPRNT-SDK-iOS-Swift#9]
We are working on building a CRM application for iPhone and iPad through Swift and Xcode. All our customers receive a StarPRNT device along with our product to manage their purchases and receipts. The StarPRNT device is model TSP100GT and at the moment of testing, it is paired through USB with a host Mac that shares the printer along the network. We're able to find and print with the TSP100GT from other Macs throughout the network but not on the iPhones and iPads. Not even the StarPRNT SDK application is able to find our printer. Other mobile applications like Printer Pro Lite however, are able to find and print with the TSP100GT. We also have experimented with the StarPRNT SDK but no luck locating our printer. We're really questioning ourselves what we're doing wrong in this case. Any help is appreciated!

**Comment by gare-bear** [comment]
Hi @stan96D,

The Star Discovery protocol is for LAN printers exclusively. The searchPrinter() method of our SDK, sends out a broadcast over the network that only Star LAN printers recognize and will respond to. We can also discover USB, Bluetooth, and BLE Star printers using APIs native to iOS. In order for USB printers to be recognized by our SDK, they must be directly connected to the device and MFi certified and the GT is not capable of either of those requirements.

In short, the TSP100GT is not supported by the StarPRNT SDK for iOS. Additionally, it has been discontinued for quite some time so I wouldn't suggest developing a solution to target this printer when we have more viable LAN solutions to fit your needs.

Although i'm not familiar with Printer Pro Lite, its possible they require some additional software to be installed on the Mac, which makes network share printers discoverable from iOS.

My simple suggestion to you would be to use a LAN-based printer such as the **TSP143IIILAN** which is fully supported by our SDK.
